- src/osal/linux/osal_udp.c
Initialise the sin_zero field to avoid compiler warnings on some
architectures. Also, not setting sin_zero may cause undefined
behaviour on some architectures.
Fix #2.
Change-Id: I72b5667c59f480ab948a50695e34792dadb8e84f
> Initialise sin_zero field

- src/osal/linux/osal_eth.c
Might get invalidated by other OSAL fixes
> Fix OSAL for Linux

- src/osal/linux/osal.c
- src/osal/linux/osal_sys.h
Use (the linux-specific and fairly undocumented) SIGEV_THREAD_ID to
avoid creating a thread whenever a timer fires.
Set PRIO_INHERIT on all mutexes.
Use clock_nanosleep and CLOCK_MONOTONIC for usleep().
Set stacksize on threads.
> OSAL improvements

- src/pf_types.h
The buffer size for periodic data must be able to handle 1400 bytes, but it was a uint8. Change to uint16.
> Increase buffer size integer type

- src/common/pf_alarm.c
- src/common/pf_ppm.c
- src/pf_types.h
* Always include the VLAN tag in cyclic data
* Add the VLAN Tag protocol identifier field
* Correct the VLAN priority (it should use the three leftmost bits)
Closes Github issue #47
> Fix VLAN tag in outgoing cyclic data frames

- src/device/pf_cmdev.c
- src/device/pf_cmrpc.c
The check of the UUID in incoming write request (in pf_cmrpc.c) is
corrected to Profinet 2.4 section 5.2.7 and 5.2.40.10.2
Check of IOCS field length (in pf_cmdev.c) is corrected to
Profinet 2.4 section 5.2.4.2.5
Closes #50
> Fix error code values sent by p-net

- src/device/pf_block_reader.h
- src/device/pf_cmrpc.c
- src/osal/linux/set_network_parameters
When doing a remote change of IP-address or name, a session is
created. Close the session immediately after an implicit read,
as there is no info wheter the session ever will be used again.
There might also be incoming RPC ping requests when changing
the IP-address. Handle those.
Improve logging and documentation.
Also the Linux script for changing the IP address etc should be
able to handle invalid (not set) default gatway.
Closes #54
> Release session after implicit read, and implement ping 

- include/pnet_api.h
- sample_app/sampleapp_common.c
Add defines for the different LLDP settings, to help end users.
Note that there are a few lower case letters in the defines to increase readability. However it is still obvious that they are defines.
> Defines for LLDP settings

- include/pnet_api.h
- src/common/pf_cpm.h
- src/device/pf_block_reader.c
- src/device/pf_block_reader.h
- src/device/pf_cmdev.c
- src/device/pf_cmdev.h
- src/device/pf_cmrdr.c
- src/device/pf_cmrpc.c
- src/pf_types.h
This allows larger responses, which is required when using more slots.
Closes #34
Closes #42
> Implement fragmented DCE RPC responses

- src/device/pf_cmdev.c
- src/device/pf_cmrpc.c
Make sure the error class is correct for the release callback.
Found with Automated RT tester.
> Set valid AR UUID in the release response

- src/common/pf_alarm.c
- src/device/pf_cmsm.c
- src/osal/linux/osal.c
Handle malloc failure and resulting memory leak and/or NULL pointer
dereferencing in src/osal/linux/osal.c
Handle possible NULL pointer dereferencing in pf_alarm.c
Found with clang-scan.
> Fix potential NULL pointers

- sample_app/main_linux.c
- sample_app/main_rtk.c
- sample_app/sampleapp_common.c
- sample_app/sampleapp_common.h
Fine tune the print-outs in the sample app, to ease understanding of the startup.
Implement helper functions for user-facing enums.
Use the pattern for enum-to-string conversion found for many non-user facing enums.
> Turn off more of the start-up printouts when not verbose

- src/common/pf_dcp.c
Make sure StartTransaction not is treated as an error
Process all DCP blocks also after one of them is indicating an error
Found with Automated RT Tester
Closes #80
> Better support for DCP transactions

- src/osal/linux/osal.c
Without this fix the script complains about missing argument
> Fix setting empty stationname on Linux

- src/device/pf_cmdev.c
Use correct enum values in order to make pnet_ar_abort() functional.
> Fix state enums for cmdev ABORT

- src/osal/linux/set_network_parameters
Found with Automated RT Tester
> Better error message for long hostname on Linux

- src/device/pf_cmrpc.c
- src/device/pf_cmrpc.h
- src/osal.h
- src/osal/linux/osal_udp.c
- src/osal/rt-kernel/osal_udp.c
- src/pf_types.h
- test/mocks.cpp
- test/mocks.h
Move Profinet port definitions from osal.h
Remove the redundant function os_udp_socket() from OSAL.
Correct argument names to os_udp_recvfrom()
> Implement fragmented request for CControl

- sample_app/main_linux.c
- sample_app/main_rtk.c
- sample_app/sampleapp_common.c
- sample_app/sampleapp_common.h
- src/device/pf_cmdev.h
This update does not implement correct behavior for the im0_filter_data request but the read result is accepted by the automated RT-tester so test does not stop on im0_filter_data. Related tests still not pass for other reasons.
Modules still defined and plugged by sample application.  Possibly the DAP module shall not be defined by the sample application but this may have other implications.
> Plug DAP module during initialization

- include/pnet_api.h
- src/common/pf_ppm.c
- src/device/pf_cmdev.c
- src/device/pf_cmrpc.c
- src/device/pf_fspm.c
Kill sessions for unknown UUIDs
Use 2 AR by default, as Automated RT Tester needs 2.
Use correct error code when invalid control command for DControl is received.
Close AR if duplicate UUID is received.
Closes #94
> Fix behavior-related issues

- src/common/pf_alarm.c
- src/device/pf_block_reader.c
Remove duplicate parsing of alarmtype field.
Use correct argument order in functions.
Closes #149
> Fix alarm parsing bug

- src/common/pf_scheduler.c
- src/common/pf_scheduler.h
- src/device/pf_block_reader.c
- src/device/pf_block_reader.h
- src/device/pf_block_writer.c
- src/device/pf_block_writer.h
- src/device/pf_cmrpc.c
- src/device/pf_cmrpc.h
- src/device/pf_cmsm.c
- src/device/pnet_api.c
- src/pf_types.h
The Ccontrol requests are now re-transmitted up to 3 times
if a response is not received from the controller within 2s.
After that the connection is aborted with the correct error code.
Also response fragments are resent if necessary
> Resend CControl requests

- src/common/pf_lldp.c
This is required for release builds on Linux, otherwise gcc will complain:
"output may be truncated writing up to 240 bytes into a region of size
between 1 and 255 [-Werror=format-truncation=]"
> Check return value of snprintf

- src/device/pf_block_writer.c
- src/device/pnet_api.c
Change field sizes to uint32 instead of uint16, and correct
argument order to function for building frame.
> Fix outgoing alarm frame structure

- src/common/pf_alarm.c
- src/common/pf_eth.c
- src/pf_types.h
Reduce code duplication by using same code for low- and high-
priority alarm frame handlers.
> Check that alarm mbox is available before writing to it

- src/device/pf_cmrpc.c
This fixes test case Different Access Ways Port 2 Port.
> Add reset of dpportcheck state variable on new AR.

- include/pnet_api.h
- src/device/pnet_api.c
- src/pf_types.h
Without this fix the error checking during startup does not work.
This leads to later segfault if the initialisation failed, but
the application not it notified.
> Correct return value from pnet_init()

- include/pnet_api.h
- sample_app/sampleapp_common.c
- src/common/pf_lldp.c
- src/common/pf_lldp.h
- src/device/pf_block_writer.c
- src/osal.h
- src/osal/linux/osal.c
- src/osal/rt-kernel/osal.c
- src/pf_types.h
- test/test_lldp.cpp
- test/utils_for_testing.cpp
Currently not used. Will be used by SNMP later on.
> Add product name to configuration. Add getters for chassis ID

- src/osal/rt-kernel/osal.c
Without this fix the compiler says:
error: uptime is used uninitialized in this function [-Werror=uninitialized]
> Fix non-initialized warning for osal.c

- src/common/pf_snmp.h
- src/pf_types.h
Helper functions for use by platform-dependent SNMP server (agent)
The purposes of this header file is to make it easier to implement the glue
code in os_snmp.c by declaring all needed functions in a single header file.
This API should not be used by other modules than the SNMP server.
> snmp: Add internal API

- src/common/pf_eth.c
- src/common/pf_eth.h
- src/pnal.h
- src/ports/linux/pnal_eth.c
- src/ports/rt-kernel/pnal_eth.c
- test/mocks.cpp
- test/mocks.h
The send function in LWIP does not accept const buffer pointer
> Remove const from buffer pointer in os_eth_send()

- sample_app/sampleapp_common.c
- src/common/pf_cpm.c
- src/device/pf_cmina.c
Fixes problem with test case AR-ASE.
Adds log error strings for a few errors to sample application.
I have not yet been able to rerun tests on latest with submodule/cmake change
> Fix cmina state transition on reset to factory

- CMakeLists.txt
- include/pnet_api.h
- options.h.in
- src/CMakeLists.txt
- src/common/pf_snmp.c
- src/common/pf_snmp.h
- src/device/pf_cmina.c
- src/device/pnet_api.c
- src/pf_includes.h
- src/pnal.h
A new file pf_snmp.c is added where each function
from header file pf_snmp.h is implemented, mostly
as stub functions returning fake data (see TODO
comments).
A cmake option to enable SNMP is added.
By default, it is set to OFF.
When enabled, the platform-specific function
os_snmp_init() is called at startup.
As no platform currently implements this function,
a link error is then generated.
> snmp: Implement internal API (stubs)

- include/pnet_api.h
- sample_app/sampleapp_common.c
- src/common/pf_lldp.c
- test/utils_for_testing.cpp
The TTL (time to live) value for outgoing LLDP frames should
always be 20 seconds, according to the Profinet standard.
Do not bother users to always supply this value.
> Remove LLDP TTL from config

- include/pnet_api.h
The ChassisID will be calculated from other parameters.
Also remove an unused lldp-related struct.
> Remove chassis_id from configuration

- src/device/pf_fspm.c
This is not an error and printing these log messages
makes test case Different Access Way Port to Port fail.
> Lower log level message on read of unsupported I&M data

- src/device/pf_fspm.c
- src/pf_types.h
What to store in the logbook is up to the stack/device vendor.
Automated RT-tester requires that at least one logbook entry
is stored. This solves this by adding entries on AR connect and
release.
> Add logbook entries

- src/ports/rt-kernel/lldp-mib.c
A warning "'strncpy' output may be truncated"
was generated. Fixed by setting response size
to zero instead of returning truncated data.
> snmp: Fix compiler warning in rt-kernel port

- src/common/pf_lldp.c
- src/common/pf_lldp.h
- src/common/pf_snmp.c
- src/common/pf_snmp.h
- src/pf_types.h
- src/ports/rt-kernel/rowindex.c
This adds an iterator object which may be used
for iterating over local ports. Previously used
functions are removed.
The rt-kernel port was updated to use the
iterator.
> snmp: Change internal API to use iterator

- src/common/pf_alarm.c
- src/common/pf_dcp.c
- src/common/pf_lldp.c
- src/common/pf_lldp.h
- src/device/pf_block_writer.c
- src/device/pf_cmdev.c
- src/device/pf_cmina.c
- src/device/pf_cmina.h
- src/device/pf_cmrpc.c
Rename getter for MAC address to indicate that it is for the
device MAC address, not any port MAC address.
> pf_lldp_get_port_config() should return a pointer

- src/common/pf_snmp.c
- src/common/pf_snmp.h
- src/ports/rt-kernel/lldp-ext-dot3-mib.c
- src/ports/rt-kernel/lldp-mib.c
- src/ports/rt-kernel/rowindex.c
- test/CMakeLists.txt
- test/mocks.cpp
- test/mocks.h
- test/test_snmp.cpp
Encoding of SNMP variables is now done in the
API functions instead of at the call site.
Some new structs were introduced containing
encoded values.
The following functions now returns new structs:
- pf_snmp_get_management_address()
- pf_snmp_get_link_status()
- pf_snmp_get_peer_management_address()
- pf_snmp_get_peer_link_status()
> snmp: Change internal API

- src/common/pf_alarm.c
- src/common/pf_cpm.c
- src/device/pf_cmdev.c
- src/device/pf_cmina.c
- src/device/pf_fspm.c
- src/device/pf_fspm.h
The return values from some informative user callbacks should not affect the stack.
It is more obvious if the functions triggering them are void.
We could possibly change the public API of the relevant callbacks
later to make them void, but for now use the same return
value meaning for all public callbacks.
Documentation on the public API will be improved in a separate
pullrequest.
> Functions triggering informative callbacks should be void

- doc/api_documentation.rst
- doc/implementation_details.rst
- include/pnet_api.h
- src/device/pnet_api.c
It is difficult to know what a function pnet_set_state() is about.
With the new name it is easier to understand that it is related
to primary and backup state of the cyclic data communication.
> Rename pnet_set_state() to pnet_set_primary_state()

- src/common/pf_alarm.c
- src/common/pf_lldp.c
- src/device/pf_cmrpc.c
- src/device/pf_cmwrr.c
- src/device/pf_cmwrr.h
- src/device/pf_fspm.c
- src/device/pf_fspm.h
- src/device/pf_pdport.c
- src/device/pf_pdport.h
- src/pf_types.h
Adds the 'const' qualifier on the buffer in the
type pf_get_info_t used for parsing a received
packet.
> Constify parsed buffer

- src/common/pf_lldp.c
- src/common/pf_lldp.h
- src/common/pf_snmp.c
- src/common/pf_snmp.h
- src/device/pf_block_writer.c
- src/pf_types.h
- src/ports/linux/mib/lldpLocManAddrTable.c
- src/ports/linux/mib/lldpRemManAddrTable.c
- src/ports/linux/mib/lldpXPnoLocTable.c
- src/ports/linux/mib/lldpXPnoRemTable.c
- src/ports/rt-kernel/lldp-ext-pno-mib.c
- src/ports/rt-kernel/lldp-mib.c
- test/mocks.cpp
- test/mocks.h
- test/test_lldp.cpp
- test/test_snmp.cpp
Stores the following TLVs from incoming LLDP
packet:
* Port Description
* Management Address
Getter functions now report error if requested
variable was not found in received LLDP packet,
even if an LLDP packet has been received.
Unit tests were added for LLDP.
> lldp: Store received optional variables

- src/common/pf_dcp.c
- src/common/pf_scheduler.h
- src/pf_types.h
The timers for clearing allowed MAC address, for flashing LED and
for sending a delayed response should be independent of eachother.
> DCP should use three different timers

- src/common/pf_lldp.c
- src/pnal.h
- src/ports/linux/pnal.c
- src/ports/rt-kernel/pnal_eth.c
- test/mocks.cpp
- test/mocks.h
- test/test_lldp.cpp
This change enables the SNMP server to return the correct ifIndex value to cllient
> lldp: Report correct ifIndex value

- CMakeLists.txt
- options.h.in
- src/common/pf_lldp.c
- src/pf_types.h
This increases the max size of port description
strings from 16 to 60 by default. The default
value of 60 is arbitrary, but hopefully large
enough to contain any received string.
> Add option to configure size of port description

- src/common/pf_snmp.c
- src/common/pf_snmp.h
- src/device/pf_block_reader.h
- src/device/pf_cmrdr.c
- src/device/pf_fspm.c
- src/device/pf_fspm.h
- src/pf_types.h
- src/ports/rt-kernel/0001-rtkernel-for-Profinet.patch
- test/test_fspm.cpp
The SNMP variable sysLocation should be the same as the I&M variable IM_Tag_Location.
This PR ensures that by letting SNMP server access IM_Tag_Location when sysLocation is requested.
The SNMP server executes from its own thread. A mutex is added for thread safety.
> Ensure consistency  for device location variable

- include/pnet_api.h
- sample_app/sampleapp_common.c
- src/common/pf_lldp.c
- src/device/pf_block_writer.c
- src/pnal.h
- src/ports/linux/pnal_eth.c
- src/ports/rt-kernel/pnal_eth.c
- test/mocks.cpp
- test/mocks.h
- test/test_lldp.cpp
- test/test_snmp.cpp
- test/utils_for_testing.cpp
Three fields were removed from the configuration
struct pnet_lldp_port_cfg_t related to the current
link status of an Ethernet port.
A new pnal function is introduced to retrieve
this information from the Ethernet driver.
The new functions are only stubs at the moment.
> api: Remove link status from configuration

- doc/api_documentation.rst
- include/pnet_api.h
- sample_app/sampleapp_common.c
- src/device/pf_cmdev.c
- src/device/pf_diag.c
- src/device/pnet_api.c
- src/pf_types.h
- test/test_diag.cpp
- test/utils_for_testing.cpp
This is requested by users that use p-net for testing of
IO-controller applications.
Add configuration flag for default diagnosis mechanism
Also improve argument validation to diagnosis functions.
> Expose low-level diagnostics functionality

- sample_app/sampleapp_common.c
- src/device/pf_cmrpc.c
Fixes a bug where the LED state from one module (in a slot) was
overwritten by data in next module/slot.
> Set sampleapp LED only from one module

- src/common/pf_lldp.c
- src/common/pf_lldp.h
- test/test_lldp.cpp
- test/utils_for_testing.cpp
Updates pf_lldp_add_management() with recent changes in management address handling.
Refactors pf_lldp_send() as to make it easier to unit test. 
Adds unit test for constructing LLDP packet to send.
> lldp: Update sent management address info

- src/common/pf_dcp.c
- src/common/pf_scheduler.c
Also better diagnostic printing of scheduler internals
This removes an invalid error message.
> Improve timer handling in pf_dcp.c

- src/ports/rt-kernel/lldp-ext-dot3-mib.c
- src/ports/rt-kernel/lldp-ext-pno-mib.c
- src/ports/rt-kernel/lldp-mib.c
- src/ports/rt-kernel/pnal_snmp.h
* If requested variable from remote device does
not exist, error NOSUCHINSTANCE is now reported
back. Previously, a zero size value was sent.
* If requested variable exists, but its value is
too large, error GENERROR is now reported back.
Previously, a zero size value was sent.
> snmp: Fix error reporting on rt-kernel

- src/device/pf_cmina.c
For test case "Behavior scenario 10" when conformance class B is used.
> SNMP: Remove syscontact and sysname for application reset

- src/common/pf_lldp.c
- test/test_lldp.cpp
Previously, if a received LLDP packet contained
multiple Management Address TLVs, only the last
one would be saved for later use. In the case
that the first TLV was the IPv4 address
and a second TLV contained an IPv6 address, the
IPv4 address would be discarded.
As Profinet uses Ipv4, this was bad.
Fixed by only saving the IPv4 address.
Unit tests were also added.
> lldp: Only save received IPv4 address, not IPv6

- src/ports/rt-kernel/0001-rtkernel-for-Profinet.patch
* Fix a defect in SNMP where wrong interface
name (ifDescr) would be returned.
* Change IP address to 192.168.0.50 as to align
with documentation.
* Put all RAM in a single memory section as to
allow for a larger heap. This enables the full
unit test program to run.
* Increase stack size for the Ethernet receive
task as to avoid overflow when running
ART Tester.
> Update rt-kernel patch file

- doc/multiple_ports.rst
- sample_app/GSDML-V2.4-rtlabs-IODevice-20201211.xml
- sample_app/sampleapp_common.c
- sample_app/sampleapp_common.h
- src/common/pf_eth.c
- src/common/pf_eth.h
- src/common/pf_lldp.c
- src/common/pf_lldp.h
- src/device/pf_port.c
- src/device/pf_port.h
- src/device/pnet_api.c
- src/pf_types.h
- src/pnal.h
- src/ports/linux/pnal_eth.c
- src/ports/linux/pnal_sys.h
- src/ports/linux/sampleapp_main.c
- src/ports/rt-kernel/dwmac1000.c
- src/ports/rt-kernel/pnal_eth.c
- src/ports/rt-kernel/pnal_sys.h
- src/ports/rt-kernel/sampleapp_main.c
- test/mocks.cpp
- test/mocks.h
- test/test_cmrpc.cpp
- test/test_dcp.cpp
- test/test_lldp.cpp
- test/utils_for_testing.cpp
- See doc/multiple_ports.rst for information on how to run configure
and run a mulitport configuration
- Verified on Raspberry Pi with additional USB ethernet interfaces
> Multiport linux support

- CMakeLists.txt
- doc/multiple_ports.rst
- include/pnet_api.h
- sample_app/GSDML-V2.4-rtlabs-IODevice-20201211.xml
- sample_app/sampleapp_common.c
- src/common/pf_lldp.c
- src/common/pf_lldp.h
- src/common/pf_snmp.c
- src/device/pf_block_reader.c
- src/device/pf_block_reader.h
- src/device/pf_block_writer.c
- src/device/pf_block_writer.h
- src/device/pf_cmrdr.c
- src/device/pf_cmwrr.c
- src/device/pf_pdport.c
- src/device/pf_port.c
- src/device/pf_port.h
- src/device/pnet_api.c
- src/pf_types.h
- src/pnal.h
- src/ports/linux/pnal.c
- src/ports/rt-kernel/pnal.c
- test/test_lldp.cpp
- test/test_port.cpp
- test/utils_for_testing.cpp
Misc updates to pass Automated RT test suite on Raspberry Pi with an usb/ethernet dongle as a second port.
Includes / rebased on #319
> Multi port updated

- cmake/rt-kernel.cmake
- src/common/pf_snmp.c
- src/ports/rt-kernel/0001-rtkernel-for-Profinet.patch
- src/ports/rt-kernel/mib2_system.c
- src/ports/rt-kernel/mib2_system.h
- src/ports/rt-kernel/pnal_snmp.c
- src/ports/rt-kernel/pnal_snmp.h
Previously, SNMP Get/GetNext requests for MIB-II
system variables were handled by lwip by either
returning values read at startup or the values
later set in SNMP Set requests. This did not allow
for the case that system variables were changes by
other means than SNMP.
To solve this, the lwip handling of MIB-II system
variables is replaced with a custom version.
Stack size for SNMP thread was also increased as
pf_snmp_get_*() functions are now called by the
SNMP thread instead of main thread, plus that use
of some static variables were eliminated.
> snmp: Don't return cached values on rt-kernel

- src/common/pf_lldp.c
- src/device/pf_block_writer.c
- src/pf_types.h
Mark lldp peer as invalid on lldp timeout.
Needs to be verified in the setup problem was originally reported.
Does implementation work with the snmp integration?
> Handle lldp rx timeout

- src/ports/rt-kernel/0001-rtkernel-for-Profinet.patch
- src/ports/rt-kernel/dwmac1000.c
- src/ports/rt-kernel/pnal_eth.c
- src/ports/rt-kernel/pnal_sys.h
This removes the xmc4-specific hook function
serving the same purpose, replacing it with a
platform-agnostic hook function.
A drawback with this solution is that the frame
receive handler now checks if frame is a Profinet
frame only after it has checked for IP/ARP
(see ethernet_input() in lwip source tree).
This will increase latency somewhat.
The patch file was updated with changes in lwip
to support this:
- LWIP_HOOK_UNKNOWN_ETH_PROTOCOL was enabled.
- An API function for setting hook function was added.
If no such hook function is set, received frames
of unknown type will be dropped.
- To avoid an extra context switch when handling received
frame, LWIP_TCPIP_CORE_LOCKING_INPUT was activated.
> rt-kernel: Use lwip hook function

- src/ports/rt-kernel/dwmac1000.c
ifSpeed would always be reported as 0 bps. Fixed by setting it in Ethernet driver's probe function.
> rt-kernel: Fix ifSpeed in SNMP MIB-II ifTable

- src/ports/rt-kernel/0001-rtkernel-for-Profinet.patch
This changes the thread priority of the Ethernet
thread to be higher than the lwip thread.
Motivation: The Ethernet thread handles incoming
Profinet packets, which are more time critical
than TCP/IP processing done by lwip thread.
> rt-kernel: Increase priority of Ethernet thread

- CMakeLists.txt
- cmake/Linux.cmake
- src/pf_types.h
- test/CMakeLists.txt
- test/mocks.cpp
- test/pf_test.cpp
- version.h.in
This PR updates gtest to fix cmake deprecation warnings, and to fix a runtime warning on embedded targets. Unfortunately gtest no longer builds on GCC version 4 or older due to incomplete c++11 support. Use of incompatible GCC is detected at configuration time and the user can disable test by setting BUILD_TESTING=OFF.
It also updates OSAL and reduces the number of global cmake settings being forced, to simplify including this project in a superproject.
> Update OSAL and gtest

- CMakeLists.txt
- include/pnet_api.h
- options.h.in
- pnet_options.h.in
- pnet_version.h.in
- sample_app/sampleapp_common.c
- sample_app/sampleapp_common.h
- src/ports/linux/pnal_filetools.c
- src/ports/linux/sampleapp_main.c
- src/ports/rt-kernel/sampleapp_main.c
Split options.h into two files. The new file pnet_options.h contains
options that are used by pnet_api.h.
Also rename and export pnet_version.h.
Fix #224.
> Export pnet options

- test/CMakeLists.txt
Also disable stack logging for SNMP, PNAL and LLDP during tests
> Control stack logging during tests with TEST_DEBUG option

- src/common/pf_dcp.c
- src/common/pf_lldp.c
- src/common/pf_lldp.h
- src/device/pf_cmina.c
- src/pf_types.h
> Many alias names

- src/device/pf_cmrpc.c
Fix unsafe use of snprintf in debug output. Issue detected by CodeQL.
> Fix unsafe use of snprintf

- include/pnet_api.h
- src/common/pf_alarm.c
- src/common/pf_alarm.h
- src/device/pf_cmdev.c
- src/device/pf_cmrpc.c
- src/device/pf_diag.h
- src/pf_types.h
Also use a define for the max_alarm_data_length we send back to the PLC
> Respect max_alarm_data_length

- include/pnet_api.h
- src/device/pf_cmdev.c
- src/device/pf_cmrpc.c
- src/device/pf_cmrpc.h
- src/device/pf_fspm.c
- test/test_cmrdr.cpp
When writing I&M data, the errorcodes set in one function were
later overwritten in another function. Fix that.
Only write I&M to file after valid requests.
Clean up error-code related defines, and some error-code related
comments.
Found with test case IP_UDP_RPC_I&M_EPM
> Do not overwrite errorcodes

- src/device/pf_block_writer.c
- src/device/pf_block_writer.h
- src/device/pf_cmdev.c
- src/device/pf_cmdev.h
Insert a proper block header before each group of diagnoses.
Note that all diagnoses in a block should have the same
API, slot, subslot and USI value.
> Sort diagnoses in USI order at readout

- sample_app/sampleapp_common.c
- sample_app/sampleapp_common.h
- src/common/pf_ppm.c
- src/common/pf_ppm.h
- src/device/pf_cmdev.c
- src/device/pf_cmrpc.c
- src/device/pf_cmsu.c
- src/device/pf_cmsu.h
- src/device/pf_cmwrr.c
- src/device/pf_cmwrr.h
- src/device/pnet_api.c
- src/pf_types.h
CMSU and CMWRR should be per AR instead of per device.
Implement modulediff when another AR owns a submodule.
Verify that PPM data have been set for a submodule, regardless of owning AR.
The output data frame ID from the PLC should be unique per device, not per AR.
Adapt sample application to be able to handle multiple connections.
Future work is needed for same input subslot to be able to send data to multiple PLCs.
Closes #131
Closes #169
> Basic adaption of pnet to multiple connections

- src/ports/rt-kernel/pnal.c
Update cmake tools to fix problem building gtest. Remove unused header
from pnal.c to allow building pf_test for integrator BSP.
> Fix rt-kernel tests

- src/device/pf_cmrpc.c
TIA portal uses EPM requests for identifying devices on the network.
Previously the sessions were not closed, resulting in "Out of session resources"
when a number of requests have been done.
Profinet uses EPM in a limited way. If we for some reason we need more advanced
EPM handling in the future, implement a timeout for each EPM session.
Closes #396
> Close EPM session after each request

- src/device/pf_pdport.c
- src/pf_types.h
If we should verify that a peer is connected, the no-peer-detected
diagnosis should be set already at startup. If the peer shows up,
the diagnosis is removed.
The previous method of setting the diagnosis after some arbitrary time
was prone to intermittent problems, as the boot time varies a lot
on Linux (for example if file system repairs are done at startup).
Dependent on the arbitrary time had timed out or not at the
diagnosis question from the ART Tester, different results appeared.
Found with the test case "Pdev_Check_onePort".
> Trigger peer-not-detected diagnosis immediately at startup

- src/common/pf_snmp.c
- src/device/pf_block_writer.c
- src/device/pf_block_writer.h
- src/device/pf_cmina.c
- src/device/pf_cmrdr.c
- src/device/pf_pdport.c
- src/ports/rt-kernel/pnal_config.h
- test/CMakeLists.txt
- test/mocks.cpp
- test/mocks.h
Mock more pnal_xxx functions
Homogenize function prototypes
Make sure that the writer functions are cleaner, and accepting just whe data that should be written.
Avoid calls to other files from the block writer functions.
> Clean up pf_block_writer.c

- sample_app/sampleapp_common.c
- sample_app/sampleapp_common.h
- src/device/pf_cmdev.c
Commit 9857aba made each AR have its own CMSU and CMWRR instance, and thus allow
multiple simultaneous connections. To support that the sample app needs to be able
to call pnet_application_ready() for each connection. A (premature) simplification
was made by calling the pnet_application_ready() already in the user callback
for state change, instead of doing a delayed transmission. It did work fine
when testing with connections.
It was later noticed however that it was not possible to do any write after the
connection had been established (normally writes are done during connection setup),
as the CMWRR was left in wrong state.
Reintroduce the delayed transmission of application_ready to solve the problem.
From an end-user point of view it would be nice to be able to call …
> Reintroduce delayed transmission of application ready

- sample_app/GSDML-V2.4-RT-Labs-P-Net-Sample-App-20210415.xml
- src/device/pf_cmdev.c
- test/test_cmdev.cpp
- test/test_cmrpc.cpp
Device-access AR is a limited version of connection as a supervisor can do.
We do not support that.
Update GSDML file to reflect that we support only one concurrent (standard) AR.
In order to support more than one AR in the future, we need to implement
ownership control of different modules in slots.
Found with ART Tester, test case "AR-ASE"
> No support for device-access AR

- src/device/pf_cmrpc.c
Any session key differences should be ignored, according to
the section 5.2.42.9.2 in Profinet Protocol v 2.4
Found with ART Tester, behavior scenario 8.
> Release should consider ARUUID but not the session key

- src/common/pf_ppm.c
- src/common/pf_ppm.h
- test/test_ppm.cpp
Increment the cycle counter value with the known difference.
Previously we based the cyclecounter value on the current time. This fix separates the two
concerns of sending the frames at correct time and to assign proper cyclecounter values.
> Base the cyclecounter value on the previous value

- src/device/pf_cmrpc.c
We are missing incoming UDP packets when closing and reopening the UDP socket.
This was found with the ART Tester, test case Alarm.
The bug is time sensitive, and is triggered when running XMC4800 with debug logging over serial cable at 460800 bit/s.
> Keep UDP socket open at session release

- CMakeLists.txt
In the ART Tester test case "APMS" a burst of 6 alarm frames is sent to the device.
Adapt the default compile time settings so all these incoming frames will fit in the
alarm input queue.
> Increase default number of alarms

- src/device/pf_cmdev.c
- src/device/pf_fspm.c
- src/device/pf_fspm.h
The function `pf_cmina_get_min_device_interval()` is located in `pf_fspm.c` so
it should be named `pf_fspm_get_min_device_interval()`
> Change name of a FSPM function

- options.h.in
- src/device/pf_cmrpc.c
- src/device/pf_diag.c
- src/device/pf_port.c
- src/device/pnet_api.c
The max number of CR information block we can store is PNET_MAX_CR.
Make sure we do not exceed this.
Also do some rudimentary validation of some of the compile time settings.
NOTE: Use the setting "Hide whitespace changes" while reviewing.
> Check number of incoming IOCR blocks

- doc/sampleapp_details.rst
- src/common/pf_alarm.c
- src/common/pf_cpm.c
- src/common/pf_dcp.c
- src/common/pf_lldp.c
- src/common/pf_ppm.c
- src/common/pf_scheduler.c
- src/common/pf_scheduler.h
- src/device/pf_cmina.c
- src/device/pf_cmio.c
- src/device/pf_cmrpc.c
- src/device/pf_cmsm.c
- src/device/pf_pdport.c
- src/device/pf_port.c
- src/pf_types.h
- test/test_scheduler.cpp
- test/utils_for_testing.cpp
- test/utils_for_testing.h
Introduce a handle object, and do some of the bookkeeping internally
in the scheduler functions.
Implement convenience functions for frequently used operations,
for example pf_scheduler_remove_if_runnning().
> Simplify usage of the scheduler

- src/device/pf_cmina.c
- src/device/pf_cmina.h
- src/device/pnet_api.c
- src/pf_types.h
- test/test_cmina.cpp
This is a debug feature, so we use the DEBUG log level right now.
We can easily adjust the log level to maybe WARNING later on if we find it useful for end users.
> Add log message if cycle time is violated

- CMakeLists.txt
- src/device/pf_cmrpc.c
Bug found with ART Tester case "Checking of sending RTC frames by the DUT" for lot of slots with parameter data to be written.
> Bugfix RPC max response length

- cmake/Linux.cmake
USE_SCHED_FIFO was not propagated to the OSAL subproject as
intended. Bump cmake-tools for newer OSAL which sets USE_SCHED_FIFO
option locally. Remove local setting of USE_SCHED_FIFO option.
> Fix USE_SCHED_FIFO option

- src/common/pf_udp.h
- src/device/pf_cmrpc.c
- src/pf_types.h
Set socket value to -1 to indicate that it is closed.
Close sockets only for the sessions initiated by us (for the CControl messaging).
Rename is_release flag to close_socket.
> Close session after incoming RPC CANCEL, FAULT and REJECT messages.

- sample_app/app_data.c
Found with "PLC tests" in conformance testing
> Fix assignment of data for led_state in sample application

- src/device/pf_block_writer.c
According to the documentation for the pf_put_padding_align() function,
the first argument should be the start_position, and the next argument should be the alignment size.
Change the usage to be according to the documentation.
Error reported by user.
> Use correct argument order for pf_put_padding_align()

- src/common/pf_lldp.c
- src/common/pf_lldp.h
Handle logging of LLDP frames where ChassisID and PortID not are strings.
> Logging of incoming non-Profinet LLDP frames

- src/common/pf_dcp.c
- test/test_dcp.cpp
Return early in functions, to decrease nesting level
Use correct return value in pf_dcp_hello_req(). Note that the return value
is not yet used in the calling code.
Set correct incoming buffer lengths in DCP tests
> Simplify DCP logic

- .gitattributes
- doc/prepare_raspberrypi.rst
- src/ports/linux/enable-rpi-gpio-pins.sh
- src/ports/linux/pnet-sampleapp.service
The /usr/bin/gpio utility from the wiringpi package is no longer available.
Use a bash script instead.
> Use a separate script to enable GPIOs on Raspberry Pi

- include/pnet_api.h
- sample_app/app_gsdml.h
- sample_app/app_utils.c
- src/common/pf_lldp.c
- src/device/pf_pdport.c
- src/device/pf_pdport.h
- src/device/pf_port.h
- src/pnal.h
- src/ports/linux/pnal.c
- src/ports/rt-kernel/pnal.c
When the link is down the MAU type can not be read from
hardware, for Linux and possibly other operating systems.
Add a configuration value for default MAU type value, to be used
when the actual value not is available.
> Better handling of Ethernet MAU types

- src/device/pf_cmrpc.c
> Error codes from write operations should be sent back to the IO-controller

- src/common/pf_bg_worker.c
- src/device/pf_cmina.c
- src/device/pf_fspm.c
- src/device/pf_pdport.c
- src/device/pnet_api.c
- test/CMakeLists.txt
- test/mocks.cpp
- test/mocks.h
This fixes problem with several background worker threads are created during tests.
> Disable background worker during unit test

- src/common/pf_dcp.c
- test/test_dcp.cpp
Previously there was no validation of the length field in DCP requests, so if
the number of bytes to read in the request was larger than the buffer size
the resulting response would contain data from memory outside the buffer.
Fixes CVE-2022-26849
Closes #490
> Validate DCP request length

- doc/api_documentation.rst
- doc/codesys_details.rst
- doc/compliancetest.rst
- doc/creating_gsdml_files.rst
- doc/getting_started_freertos.rst
- doc/profinet_basics.rst
- doc/spelling_wordlist.txt
- doc/use_with_siematic.rst
- doc/using_codesys.rst
- include/pnet_api.h
- src/common/pf_bg_worker.h
- src/common/pf_file.c
- src/common/pf_lldp.c
- src/common/pf_ppm.c
- src/common/pf_scheduler.h
- src/common/pf_snmp.h
- src/pf_types.h
- test/test_port.cpp
Renamed "typedef enum pnet_im_supported_value" to pnet_im_supported_values.
The more important pnet_im_supported_values_t is not modified.
> Improve documentation week 22

- src/ports/rt-kernel/0001-rtkernel-for-Profinet.patch
This updates the p-net patch for rt-kernel for the 2021.1 release.
Fix #476.
> rt-kernel: update patch for 2021.1

- src/device/pf_pdport.c
Fixes problem detected in ART Tester Diagnosis test. In a setup with two ports,  a port name mismatch diagnosis was set even if device "D" reported the expected LLDP information.
Original problem reproduced on master branch. 
Test passes with this fix added.
> Fix problem in PDPortDataCheck

- src/ports/STM32Cube/sampleapp_main.c
- src/ports/rt-kernel/sampleapp_main.c
Checked that rt-kernel sample starts up on xmc board and that it can be configured using Proneta tool.
> Fix build error for rt-kernel and FreeRTOS ports

- src/device/pf_block_reader.c
- src/device/pf_block_reader.h
- src/device/pf_cmrpc.c
- src/pf_types.h
Here are two fixes that add some sanity checks and their respective failure responses to the controller.
> Two protocol fixes

- src/ports/STM32Cube/pnal_eth.c
- src/ports/rt-kernel/0001-rtkernel-for-Profinet.patch
- src/ports/rt-kernel/pnal_eth.c
Bug fix for xemacps descriptor queues becomeing corrupt, due to both lwip and p-net using the same driver but p-net does not check if the driver is busy. To resolve the issue, the LWIP core needs to be locked before it is called by p-net.
> Lock LWIP before p-net linkoutput call

- src/device/pf_cmrpc.c
For outgoing fragmented RPC messages, the header size was accounted for an extra time for each fragment except the first one. This change corrects that.
> Correct the accounting of outgoing RPC fragment sizes

- doc/getting_started_LAN9662.rst
- src/drivers/lan9662/add_inbound_vcap_rule.sh
- src/drivers/lan9662/add_outbound_vcap_rule.sh
- src/drivers/lan9662/del_vcap_rule.sh
With the latest kernel, the syntax for adding/removing vcap entries has been changed. Therefore update also the scripts to use new syntax. While at this update also the documentation.
> Update vcap syntax
