rtlabs-com/p-net

sample_app/GSDML-V2.33-rt-labs-IODevice-20191008.xml
Simple sample IO Device GSDML file
Three plugable modules
8 Bit Inputs
8 Bit Ouputs
8 Bit Inputs/8 Bit Outputs
=> Add sample_app IO Device GSDML file

src/common/pf_alarm.c
Fixes Github #9, as reported by @Svenson12
=> Correct VLAN status definition. Fixes Github #9

include/pnet_api.h, src/device/pf_block_reader.h, src/device/pf_cmdev.c, src/pf_types.h, test/test_cmrdr.cpp, test/test_dcp.cpp, test/test_diag.cpp, test/test_lldp.cpp, test/test_osal.cpp, test/test_pnetapi.cpp
Also one trivial diagnostic print-out tweak.
=> Minor in-code documentation fixes

cmake/Linux.cmake, src/osal/linux/osal.c
Support use of SCHED_FIFO on Linux.
Change-Id: I5fe6cec24767839811b8a00d89e7c780d8929233
=> Support linux realtime scheduling

sample_app/main_linux.c
Change station name from command line. Print more diagnostic data. Read IP address from Linux kernel.
=> Fix file closing bug in sample_app. 

src/device/pf_cmrpc.c, test/test_cmrpc.cpp
=> Fix bug in parameter write response.

src/device/pf_cmdev.c, src/device/pf_cmdev.h, src/pf_types.h, test/test_cmdev.cpp
=> Fix bug when using output modules

src/device/pf_block_writer.c, src/device/pf_cmrpc.c, src/device/pf_cmsm.c, src/device/pf_cmsm.h
And handle that AR is null for explicit reads
=> Correct implicit read also when there are no slots in use

cmake/Linux.cmake, include/pnet_api.h, src/device/pf_cmina.c, src/device/pnet_api.c, src/osal.h, src/osal/linux/osal.c, src/osal/linux/set_network_parameters, src/osal/rt-kernel/osal.c, src/pf_types.h, test/mocks.cpp, test/mocks.h
Implement missing functionality in osal.c for Linux.
Use a script for adapting manuipulation to different Linux
distributions.
=> Set IP address on Linux

src/common/pf_cpm.c, src/common/pf_cpm.h, src/device/pf_block_reader.c, src/device/pf_block_reader.h, src/device/pf_cmdev.c, src/device/pf_cmdev.h, test/CMakeLists.txt, test/test_block_reader.cpp, test/test_cmdev.cpp, test/test_cpm.cpp
* Make sure pf_cpm_check_cycle() only returns 0 or -1. This change does not affect existing code, as the only usage check whether the return value is exactly 0.
* Change log level in pf_get_bits()
* Sort entries in test/CMakeLists.txt
* Improve documentation for tested functions.
=> Implement more unittests

src/common/pf_dcp.c
Found with Automated RT Tester
=> Make sure no other MAC address is used in DCP communication

src/common/pf_dcp.c, src/device/pf_cmina.h
Found with Automated RT Tester
=> Include MAC address in DCP get response

src/device/pf_cmrpc.c
=> Close UDP socket after use

doc/prepare_raspberrypi.rst, sample_app/pnet-sampleapp.service
Add a systemd unit file.
Add documentation how to install it on Raspberry Pi.
Closes #93
=> Enable autostart of sample application on Rasperry Pi

cmake/Linux.cmake, doc/api_documentation.rst, doc/getting_started_linux.rst, include/pnet_api.h, sample_app/main_linux.c, sample_app/main_rtk.c, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, sample_app/set_profinet_leds_linux, sample_app/set_profinet_leds_linux.raspberrypi, src/common/pf_dcp.c, src/device/pf_cmina.c, src/device/pf_fspm.c, src/device/pf_fspm.h, src/osal.h, src/osal/linux/osal.c, src/osal/rt-kernel/osal.c, test/mocks.cpp, test/mocks.h, test/test_dcp.cpp, test/utils_for_testing.cpp, test/utils_for_testing.h
Remove LED and button related functionality from OSAL.
Closes #91
=> Implement callback for signal LED state change

src/device/pf_cmrpc.c
A single write should only have one response block.
For multiple write there should be an initial block signalling
that it is a multiple write, and then the individual response blocks.
Closes #111
=> Fix single write

src/device/pf_cmina.c, src/device/pf_cmina.h, test/test_cmina.cpp
Implementation of validation functions and test cases
=> Add  dcp validation

include/pnet_api.h, src/common/pf_cpm.c, src/common/pf_dcp.c, src/device/pf_block_reader.c, src/device/pf_block_writer.c, src/device/pf_cmdev.c, src/device/pf_cmdev.h, src/device/pf_cmina.c, src/device/pf_cmsu.c
=> Code quality improvement

src/device/pnet_api.c
Fixes problem with uninitialized log book
#82
=> Initialize stack variable to zero after allocation

include/pnet_api.h, sample_app/sampleapp_common.c, src/common/pf_dcp.c, src/common/pf_lldp.c, src/common/pf_scheduler.h, src/pf_types.h, test/test_dcp.cpp, test/utils_for_testing.cpp
Use the station name in LLDP frames
Send LLDP frame after all DCP set and get
Closes #139
=> Implement periodic sending of LLDP frames

include/pnet_api.h, sample_app/main_linux.c, sample_app/sampleapp_common.c, sample_app/set_profinet_leds_linux, src/common/pf_alarm.c, src/common/pf_dcp.c, src/device/pf_cmdev.c, src/device/pf_cmina.c, src/device/pf_cmina.h, src/device/pf_cmrpc.c, src/device/pf_fspm.c, src/device/pf_fspm.h, src/osal.h, src/osal/linux/osal.c, src/osal/linux/set_network_parameters, src/osal/rt-kernel/osal.c, src/pf_types.h, test/mocks.cpp, test/mocks.h
OSAL functions to save and load binary blobs
Add function to get MAC address from config
Improve logging of IP addresses
Rename variables to better reflect their usage
Change revision prefix in sample application
Closes #92
=> Implement storing of IP parameters between runs

src/osal/linux/osal_eth.c
=> Use correct buffer size for recv() of raw Ethernet frames

src/common/pf_ppm.c, src/common/pf_ppm.h, src/pf_types.h, test/test_ppm.cpp
Based on contributions by atomic-3dpenguin
=> Calculate cyclecounter for peridic data

CMakeLists.txt, doc/creating_gsdml_files.rst, include/pnet_api.h, options.h.in, sample_app/sampleapp_common.c, src/device/pf_block_writer.c, src/device/pf_cmdev.c, src/device/pf_fspm.c, src/device/pf_fspm.h, src/device/pnet_api.c, test/CMakeLists.txt, test/test_fspm.cpp, test/utils_for_testing.cpp
Basic validation of the configuration
Rename a member in im_0_data in the configuration
=> Move the min_device_interval setting to the configuration

src/common/pf_alarm.c, src/common/pf_dcp.c, src/common/pf_eth.c, src/common/pf_lldp.c, src/common/pf_ppm.c, src/device/pf_cmina.c, src/device/pf_cmina.h, src/device/pf_cmrpc.c, src/osal.h, src/pf_types.h
Add docstrings for socket usage in osal.h
Remove duplicate define from osal.h
Based on contributions by atomic-3dpenguin
=> Implement interface statistics counters

src/common/pf_cpm.c
See Profinet 2.4 protocol, table 630.
=> Change error code for CPM timeout

doc/implementation_details.rst, include/pnet_api.h, src/device/pf_cmdev.c, src/device/pf_cmina.c, src/device/pf_cmina.h, src/device/pf_cmrpc.c, src/device/pf_cmrpc.h, src/osal/rt-kernel/osal.c
Rename printing stack functions to xxx_show()
=> Remove printf from stack

doc/capturing_packets.rst, src/common/pf_alarm.c, src/common/pf_cpm.c, src/common/pf_dcp.c, src/common/pf_ppm.c, src/common/pf_scheduler.c, src/common/pf_scheduler.h, src/device/pf_cmio.c, src/device/pf_cmrpc.c, src/device/pf_cmsm.c, src/pf_types.h, test/test_ppm.cpp, test/test_scheduler.cpp
Add documentation how to measure periodicity using Wireshark
=> Improve scheduling for sending of periodic data

include/pnet_api.h, sample_app/main_linux.c, sample_app/main_rtk.c, sample_app/sampleapp_common.h, src/common/pf_alarm.c, src/device/pf_cmdev.c, src/device/pf_cmina.c, src/device/pf_cmrpc.c, src/device/pf_fspm.c, src/device/pf_fspm.h, src/device/pnet_api.c
=> Add Linux command line option to show memory details

src/common/pf_eth.c
Based on contributions from atomic-3dpenguin
=> Clean up pf_eth_recv by calculating a frame position

doc/api_documentation.rst, include/pnet_api.h, sample_app/main_linux.c, sample_app/main_rtk.c, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, src/common/pf_alarm.c, src/common/pf_alarm.h, src/device/pf_block_writer.c, src/device/pf_block_writer.h, src/device/pf_fspm.c, src/device/pf_fspm.h, src/device/pnet_api.c, src/pf_types.h, test/utils_for_testing.cpp, test/utils_for_testing.h
Improved transport ACK (TACK) handling.
Corrected writing of outgoing messages.
Closes #147
=> Additional data for public alarm ack API

include/pnet_api.h, src/common/pf_lldp.c, src/common/pf_lldp.h, src/pf_types.h
Rename functions to pf_lldp_xxx
Use consistent indentation
=> Improve LLDP logging

src/osal/linux/osal_eth.c
Depending on the Ethertype, some incoming frames are dropped
at later processing
=> Allow reception of LLDP frames in Linux

sample_app/main_linux.c, sample_app/main_rtk.c, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h
When pressing button2, cycle between sending alarms, setting
diagnosis and writing to logbook.
=> Split out more of the common funtionality in the sample application

include/pnet_api.h, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, src/device/pf_block_writer.c, src/device/pf_cmrdr.c
Separate sample_app specific defines from stack defines
=> Use proper defines for subslot and submodules

include/pnet_api.h, sample_app/main_linux.c, sample_app/main_rtk.c, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, src/common/pf_ppm.c, src/common/pf_ppm.h, src/device/pf_cmdev.c, src/device/pf_fspm.c, src/device/pf_fspm.h, test/utils_for_testing.cpp
I still have an issue with led / button on sample application.
Merge should wait until "Use proper defines for subslot and submodules " is merged
=> Behavior scenario 2

include/pnet_api.h, src/device/pf_cmdev.c, src/device/pf_cmdev.h, src/device/pf_fspm.c, src/device/pf_fspm.h, src/device/pnet_api.c
Show logbook and diagnosis details
=> Save logbook to file

src/common/pf_ppm.c, src/device/pf_cmdev.c, src/device/pf_cmina.c, src/device/pf_cmsu.c
When running tests the commits in PR191 Behavior Scenario 2 was also included
=> Misc updates to pass test case AR-ASE

src/CMakeLists.txt, src/device/pf_block_reader.c, src/device/pf_block_reader.h, src/device/pf_block_writer.c, src/device/pf_block_writer.h, src/device/pf_cmrpc.c, src/device/pf_cmrpc_epm.c, src/device/pf_cmrpc_epm.h, src/pf_types.h
Based on contributions in https://github.com/rtlabs-com/p-net/pull/151
by atomic-3dpenguin
-------------------------
Epm check in user scenario 10 passes
Still problems with IP_UPD_RPC_I&M_EPM test case
=> Add RPC End Point Mapper

src/device/pf_block_writer.c
Breakout witing maint_status to separate function
Correct usage of slot number and subslot number for
filtering and writing.
=> Refactor writing diagnosis to buffer

include/pnet_api.h, sample_app/sampleapp_common.c, src/device/pf_cmina.c, src/pf_types.h, test/utils_for_testing.cpp
Fixes IP_UDP_I&M_EPM together with #219 and #223
=> Fix testcase IP_UDP_I&M_EPM

include/pnet_api.h, src/common/pf_lldp.c, src/common/pf_lldp.h, src/common/pf_snmp.c, src/common/pf_snmp.h, src/device/pf_block_writer.c, src/pf_types.h, test/test_lldp.cpp, test/utils_for_testing.cpp
Implements LLDP getter functions, which are called
when SNMP requests are received.
Also adds unit tests for LLDP getter functions.
=> snmp: Get LLDP variables

include/pnet_api.h, src/device/pf_cmina.c, src/device/pf_fspm.c
Avoid saving to file if not required.
=> Don't save logbook to file

src/device/pf_block_reader.c, src/device/pf_block_reader.h, src/device/pf_cmrdr.c, src/device/pf_cmwrr.c, src/device/pf_pdport.c, src/pf_types.h
Prepare for storing multiple peer info per port.
=> Improve logging for cmrdr.c and cmwrr.c

src/device/pf_cmrdr.c
=> Fix data size comparison off-by-one

src/CMakeLists.txt, src/common/pf_lldp.c, src/common/pf_lldp.h, src/common/pf_snmp.c, src/common/pf_snmp.h, src/device/pf_block_writer.c, src/device/pf_block_writer.h, src/device/pf_cmrpc.c, src/device/pf_cmwrr.c, src/device/pf_pdport.c, src/device/pf_pdport.h, src/device/pf_port.c, src/device/pf_port.h, src/pf_includes.h, src/pf_types.h, test/CMakeLists.txt, test/test_lldp.cpp, test/test_port.cpp
Implement pf_port.c file for the data retrieval
=> Prepare port runtime data storage for multiple ports

include/pnet_api.h, sample_app/sampleapp_common.c, src/common/pf_alarm.c, src/common/pf_alarm.h, src/common/pf_lldp.c, src/device/pf_cmdev.c, src/device/pf_cmdev.h, src/device/pf_cmrdr.c, src/device/pf_diag.c, src/device/pf_diag.h, src/device/pf_pdport.c, src/device/pf_pdport.h, src/device/pnet_api.c, src/pf_types.h, test/test_alarm.cpp, test/test_cmrdr.cpp, test/test_diag.cpp
With updates included in this PR the first step of the Diagnostics test case passes
=> Rework diagnostics

src/common/pf_lldp.c, src/common/pf_lldp.h, src/device/pf_pdport.c
Also make two LLDP functions private.
=> Enable LLDP transmission when no PDport adjust is active

src/common/pf_dcp.c
Problem detected in test case DCP Access. Problem was that
timeouts were not removed but only added giving a random behavior.
=> Fix DCP SAM

src/common/pf_lldp.c, test/test_lldp.cpp
Refactor pf_lldp_parse_packet() by moving code to separate sub-functions.
This reduces nesting and code size of pf_lldp_parse_packet(), making it easier to read.
Any change in functionality is unintentional.
Unit tests were also added.
=> lldp: Refactor parsing of received packet

src/device/pf_pdport.c
Improve logging for pdport file reading
=> Overwrite pdport file if necessary instead of deleting it

doc/prepare_raspberrypi.rst, doc/tutorial.rst, include/pnet_api.h, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, sample_app/set_profinet_leds_linux, sample_app/set_profinet_leds_linux.raspberrypi, src/ports/linux/sampleapp_main.c, src/ports/rt-kernel/sampleapp_main.c
Improve sampleapp handling of LEDs and buttons
=> Disable sample app outputs at STOP and ABORT

doc/multiple_ports.rst, include/pnet_api.h, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, src/common/pf_lldp.c, src/common/pf_lldp.h, src/common/pf_scheduler.c, src/device/pf_block_writer.c, src/device/pf_cmina.c, src/device/pf_cmrpc_epm.c, src/device/pf_fspm.c, src/device/pnet_api.c, src/pf_types.h, src/ports/linux/sampleapp_main.c, src/ports/rt-kernel/sampleapp_main.c, test/test_fspm.cpp, test/test_lldp.cpp, test/utils_for_testing.cpp, test/utils_for_testing.h
This PR is marked draft since I need to check that updates aligns with required updates in pnet struct before its merged.
=> Multi port

doc/network_topology_detection.rst, src/common/pf_eth.c, src/common/pf_eth.h, src/common/pf_lldp.c, src/common/pf_lldp.h, src/common/pf_udp.c, src/common/pf_udp.h, src/device/pf_block_writer.c, src/device/pf_block_writer.h, src/device/pf_cmina.c, src/device/pf_cmina.h, src/device/pf_pdport.c, src/device/pf_pdport.h, src/device/pf_port.h, src/pf_types.h, src/pnal.h, src/ports/linux/pnal.c, src/ports/linux/pnal_eth.c, src/ports/rt-kernel/pnal.c, src/ports/rt-kernel/pnal_eth.c, test/mocks.cpp, test/mocks.h
Adapt pnal ethernet-related functions to use the interface name as argument.
=> Read interface statistics from operating system via pnal

src/common/pf_alarm.c, src/common/pf_dcp.c, src/common/pf_lldp.c, src/common/pf_lldp.h, src/common/pf_snmp.c, src/device/pf_block_writer.c, src/device/pf_cmdev.c, src/device/pf_cmina.c, src/device/pf_cmina.h, src/device/pf_cmrpc.c, src/device/pf_cmrpc_helpers.c, src/device/pf_fspm.c, src/device/pf_pdport.c, src/device/pf_port.c, src/device/pf_port.h, src/pf_types.h, src/pnal.h
Implement getters and setters for cmina internal data
Add TODOs for existing thread-safety problems
=> Move port configuration getter to pf_port.c 

sample_app/sampleapp_common.c
Subslots are numbered for example 0x8001, and we have around 5
positions in an array to store subslot data (for each slot).
Typically the variable 'subslot' is used for the subslot number.
Clarify the difference between the subslot number and the index into the
array.
Also improved NULL-check
=> Rename sampleapp variables

src/ports/rt-kernel/dwmac1000.c
Let Ethernet driver update counters in SNMP MIB2
table for each sent and for each received Ethernet
frame.
This change was taken from the rt-kernel repository (version 2020.1).
=> rt-kernel: Update MIB2 counters

src/ports/linux/mib/lldpConfigManAddrTable.c, src/ports/linux/mib/lldpLocManAddrTable.c, src/ports/linux/mib/lldpRemManAddrTable.c
Fix three instances where pf_snm_management_address_t was used
incorrectly.
Change-Id: I616c85135662e2c2b144d6ef261600e7a2f73aa1
=> Fix use of pf_snmp_management_address_t

sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, src/pnal.h, src/ports/linux/pnal.c
=> Handle invalid IP addresses on Linux

src/ports/linux/pnal.c
This is required for file changes to appear on disk, even if the
power is removed soon after writing. Tested with ART tester test
case "Topology discovery check".
Bug reported by Giuseppe.
=> Use syncronized file saving on Linux 

src/common/pf_lldp.c, src/device/pf_pdport.c, src/device/pf_port.c, src/device/pnet_api.c, src/pf_types.h
To avoid problems with Microsoft compilers
=> Rename "interface" struct

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, README.md
Let CodeQL scan code and PR:s for security vulnerabilities.
=> Enable CodeQL semantic code analysis

sample_app/sampleapp_common.c
=> Signal ready_for_data after all local data has been set

src/common/pf_alarm.c, src/device/pf_diag.c
Simplified logic by using multiple returns at error conditions.
Added error logging for invalid data pointers.
=> Fix two potential memcpy of null pointers

src/ports/linux/pnal_udp.c, src/ports/rt-kernel/pnal_udp.c
=> Set SO_REUSEADDR for UDP sockets to enable fast restarts

src/ports/linux/pnal.c
We use the unbuffered API for saving files, as we need to make sure
the files end up on disk immediately. So it is reasonable to use
the unbuffered API also for reading files.
=> Use unbuffered file reading on Linux

cmake/Linux.cmake, cmake/rt-kernel.cmake, sample_app/GSDML-V2.4-RT-Labs-P-Net-Sample-App-20210507.xml, sample_app/app_data.c, sample_app/app_data.h, sample_app/app_gsdml.c, sample_app/app_gsdml.h, sample_app/app_log.c, sample_app/app_log.h, sample_app/app_utils.c, sample_app/app_utils.h, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, src/ports/linux/sampleapp_main.c, src/ports/rt-kernel/sampleapp_main.c, test/utils_for_testing.cpp, test/utils_for_testing.h
We should rerun Auomated RT-tester suite on both rt-kernel and linux targets before merging. 
Commit message:
Split sample application into several files.
- Move utilities to separate file
- Add log macros for sample application
- Move gsdml parameters to specific header
- Move process data and parameters to separate file
- Add unique submodule ids
- GSDML has changed. Needs to be reloaded in engineering tool and
ART tester.
- Align sampleapp_main for linux and rt-kernel
=> Refactor sample application

src/device/pf_cmrpc.c
Improve logging by adding fragmentation log info.
=> Add rpc fragmentation log message

src/CMakeLists.txt, src/common/pf_bg_worker.c, src/common/pf_bg_worker.h, src/common/pf_lldp.c, src/device/pf_cmina.c, src/device/pf_cmina.h, src/device/pf_fspm.c, src/device/pf_fspm.h, src/device/pf_pdport.c, src/device/pf_pdport.h, src/device/pf_port.c, src/device/pnet_api.c, src/pf_includes.h, src/pf_types.h, src/ports/linux/pnal_config.h, src/ports/linux/sampleapp_main.c, src/ports/rt-kernel/pnal_config.h, src/ports/rt-kernel/sampleapp_main.c, test/test_fspm.cpp, test/test_lldp.cpp
Handles saving to file and reading ethernet status.
=> Add background worker

sample_app/app_data.c, sample_app/app_utils.c, sample_app/sampleapp_common.c, src/ports/linux/sampleapp_main.c
=> Improve log level handling for Linux sample app

src/device/pf_cmdev.c
Bug reported by Jan Vasina
Closes #440
=> Use api_id instead of api_ix

src/device/pf_cmrpc.c, src/pf_types.h
Reported by Jan Vasina
Closes #444
=> Set serial_low and serial_high in RPC responses

src/device/pf_cmdev.c, src/device/pf_pdport.c, src/device/pf_pdport.h, src/ports/STM32Cube/pnal.c, test/mocks.cpp, test/utils_for_testing.h
Fix error setting mechanism in case of too slow ports
=> Check that at least one of the Eth ports is fast enough

sample_app/app_gsdml.h, sample_app/app_utils.c
Use snprintf() instead of strcpy() in sample_app/app_utils.c
=> Use defines for OEM vendor etc in sampleapp

src/device/pf_port.c, test/test_port.cpp
-Werror=aggressive-loop-optimizations
Change-Id: I51fc2724bb212e5ea03278a8500a78820e9a5fb5
=> Fix warning in pf_port

sample_app/GSDML-V2.4-RT-Labs-P-Net-Sample-App-20220324.xml, sample_app/app_data.c, sample_app/app_data.h, sample_app/app_gsdml.c, sample_app/app_gsdml.h, sample_app/app_utils.c, sample_app/app_utils.h, sample_app/sampleapp_common.c, sample_app/sampleapp_common.h, src/ports/STM32Cube/sampleapp_main.c, src/ports/linux/sampleapp_main.c, src/ports/rt-kernel/sampleapp_main.c
Update GSDML file accordingly
Simplify logic in sampleapp subslot handling
=> Add more modules to the sample app

src/ports/linux/pnal_eth.c
Some linux solutions needs this addition to receive
Profinet multicasts. DCP Identity all do not work
without it.
Change-Id: Ia7fb34d1c23e1ebcacda2dd76964c2ae488584c3
=> Join profinet multicast group (linux)

src/device/pf_cmina.c
Simplify logic in pf_cmina_dcp_set_commit() by returning early.
Increase log level to INFO.
=> Show a log message if the stack refuses to change IP address

CMakeLists.txt, include/pnet_api.h, src/CMakeLists.txt, src/common/pf_cpm.c, src/common/pf_cpm.h, src/common/pf_cpm_driver_sw.c, src/common/pf_cpm_driver_sw.h, src/common/pf_ppm.c, src/common/pf_ppm.h, src/common/pf_ppm_driver_sw.c, src/common/pf_ppm_driver_sw.h, src/device/pf_cmdev.c, src/device/pf_cmsu.c, src/device/pf_diag.c, src/device/pnet_api.c, src/drivers/drivers.cmake, src/drivers/drivers_options.cmake, src/pf_driver.h, src/pf_includes.h, src/pf_types.h, test/CMakeLists.txt
This includes move samples application folder #487.
Is naming ok? 
There should be minimal functional change in ppm and cpm. 
Note that project does not build if driver is enabled but no driver is selected (driver which is being developed is not available at this point). Is the error information for this enough?
=> Add ppm cpm driver concept

include/pnet_api.h, samples/pn_dev/app_data.c, samples/pn_dev/app_data.h, samples/pn_dev/app_utils.c, samples/pn_dev/app_utils.h, samples/pn_dev/sampleapp_common.c, samples/pn_dev/sampleapp_common.h
Partly reviewed in #484
Created a new PR as the samples directory was moved.
=> Modify api usage order and iops handling

samples/pn_dev_lan9662/app_gsdml.h, samples/pn_dev_lan9662/app_utils.c, samples/pn_dev_lan9662/app_utils.h, samples/pn_dev_lan9662/sampleapp_common.c, samples/pn_shm_tool/shm_echo_all.sh, samples/pn_shm_tool/shm_read_all.sh, samples/pn_shm_tool/shm_write_all_inputs.sh, src/drivers/lan9662/src/pf_lan9662_mera.c
Only affects LAN9662 sample and driver. 
Fixes issues detected during testing.
=> Lan9662 fix 1

src/common/pf_dcp.c
Fixes memory leak in DCP. 
Closes #500
The problem could for example be triggered by repeatedly clicking the refresh button in Proneta.
=> bugfix DCP memory leak

.github/workflows/build.yml
Add workflow_dispatch, and use apt-spy2 to find Ubuntu mirrors.
=> Modify the Github workflow

src/device/pf_cmrpc.c
Fixes a session leak found during Security Level 1 testing.
=> Fix RPC session leak

src/device/pf_plugsm.c
Fixes build issues on rt-kernel target.
=> Update log message format

test/test_dcp.cpp
6930de2 added an additional call to pnal_set_ip_suite.
=> test_dcp: Fix set_ip_suite_count
